# Generated by Django 2.0 on 2019-02-18 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Nigeria', max_length=100, unique=True)),
                ('area', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='General', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11, message='phone number must be 11 - 14 characters long')])),
                ('email', models.EmailField(max_length=150, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='honest.Area')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='honest.Category')),
            ],
        ),
    ]
