# Generated by Django 2.0 on 2019-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
