# Generated by Django 2.0 on 2019-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0002_auto_20190218_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='web-developer'),
            preserve_default=False,
        ),
    ]
