# Generated by Django 2.0 on 2019-02-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='lagos'),
            preserve_default=False,
        ),
    ]
