# Generated by Django 2.0 on 2019-02-20 22:41

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('honest', '0005_area_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='General', help_text='Category of Service Provided', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Valid email address', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Last name (surname)', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(help_text='Location (state)', on_delete=django.db.models.deletion.PROTECT, related_name='location', to='honest.Area'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(help_text='phone number 11- 14 digits allowed', max_length=14, validators=[django.core.validators.MinLengthValidator(11, message='phone number must be 11 - 14 characters long')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.ForeignKey(help_text='Service', on_delete=django.db.models.deletion.PROTECT, related_name='service', to='honest.Category'),
        ),
    ]
