# Generated by Django 2.0 on 2019-03-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0006_auto_20190220_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.CharField(blank=True, max_length=360)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='honest.Person'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='honest.UserProfile'),
        ),
    ]
