# Generated by Django 2.0 on 2019-03-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0007_auto_20190313_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1 Star', 1), ('2 Stars', 2), ('3 Stars', 3), ('4 Stars', 4), ('5 Stars', 5)], default=5)),
                ('review_text', models.CharField(blank=True, max_length=360)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='honest.Person')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='honest.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
