# Generated by Django 2.0 on 2019-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0008_auto_20190314_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.CharField(default='Fair', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
    ]
