# Generated by Django 2.0 on 2019-03-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honest', '0010_review_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='honest.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='honest.UserProfile'),
        ),
    ]
